version: "3"
services:
  app:
    container_name: smart-root
    tty: true
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - .:/home/smart-root
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
